spring:
   datasource:
      # useSSL=false表示不使用加密通讯，本机的数据库不需要加密，加密性能差
      # serverTimezone=CST表示指定服务器的时区，CST=China Standard Time 中国标准时
      url: jdbc:mysql://127.0.0.1:3306/weixin?useSSL=false&&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: weixin
      password: 1234
   jpa:
   #自动生成数据库的表，DDL表示数据定义语言，通常用来管理表结构的
      generate-ddl: true
   #运行时生成的sql语句打印出来
      show-sql: true
   redis:
      host: 120.77.212.25
      port: 6379
      #数据库只能0~15，因为目前使用的是默认设置，最多16个数据库
      database: 15

#由于现在没有web模块，所以不需要端口
#server.port: 8090
